# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Ultra
tagline:          'HTML UI for Games'
description:      'High-Performance<br>HTML UI for Games'
url:              http://ultra.vg
baseurl:          /

author:
  name:           'Adam Simmons'
  url:            https://twitter.com/adamjsimmons

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
